sudo: required
language: node_js
node_js:
  - "0.10.29"
addons:
  code_climate:
    repo_token: 7bce0e0c7addf93f1aa79830b3821e3c347c04f22ceec134e480598b8fb3332b
after_script:
  - codeclimate-test-reporter < public/tests/coverage/lcov.info
